---

root: true

extends:
  - "airbnb-base"
  - "react-app"


parser: "@typescript-eslint/parser"

plugins: ["@typescript-eslint"]

rules:
  no-console: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  max-len: [2, {"code": 120, "tabWidth": 2, "ignoreUrls": true}]
  import/prefer-default-export: "off"
  "@typescript-eslint/explicit-function-return-type": "off"

overrides:
- files:
  - "*.ts"
  - "*.tsx"

  extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  # - "plugin:@typescript-eslint/recommended-requiring-type-checking"

  rules:
    "@typescript-eslint/explicit-function-return-type": ["error"]

  parserOptions:
    project:
    - "./tsconfig.json"