---

root: true

extends:
  - "airbnb-base"
  - "react-app"


settings:
  import/resolver:
    node:
      extensions:
      - ".ts"
      - ".tsx"
      - ".js"
      - ".jsx"

parser: "@typescript-eslint/parser"

plugins: ["@typescript-eslint"]

rules:
  no-console: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  max-len: [2, {"code": 150, "tabWidth": 2, "ignoreUrls": true}]
  import/prefer-default-export: "off"
  "@typescript-eslint/explicit-function-return-type": "off"
  no-shadow: "off"
  "@typescript-eslint/no-shadow": ["error"]

overrides:
- files:
  - "*.ts"
  - "*.tsx"

  extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:import/errors"
  - "plugin:import/warnings"
  - "plugin:import/typescript"


  # - "plugin:@typescript-eslint/recommended-requiring-type-checking"

  rules:
    "@typescript-eslint/explicit-function-return-type": ["error"]
    max-len: [2, {"code": 150, "tabWidth": 2, "ignoreUrls": true}]
    "import/extensions":
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never

  parserOptions:
    project:
    - "./tsconfig.json"